### ISSUE TITLE
請問要如何增添"此字幕僅供學習交流，請勿用於商業用途。"這一行？

### ISSUE THREAD

**Issue by pb6210** [ewwink/python-srt2ass#1]
If i need the following format, how to add "Dialogue: 0,0: 00: 00.00,0: 00: 03.85, Logo ,, 0,0,0 ,, Dialogue: 0,0:00:00.00,0:00:03.85,Logo,,0,0,0,,此字幕僅供學習交流，請勿用於商業用途。 " This line

[Script Info]
ScriptType: V4.00+
Collisions: Reverse
PlayResX: 1280
PlayResY: 720
Timer: 100.0000
WrapStyle: 0
ScaledBorderAndShadow: no

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Microsoft JhengHei,68,&H0000FFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,3,2,50,50,12,1
Style: Comment,Microsoft JhengHei,40,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,50,50,200,136
Style: Preview,Microsoft JhengHei,65,&H00FFFFFF,&H000000FF,&H00000080,&H64000000,-1,0,0,0,100,100,0,0,1,2,3,1,50,50,12,1
Style: Review,Microsoft JhengHei,65,&H120456DF,&H000000FF,&H00000000,&H00000000,-1,-1,0,0,100,100,0,0,1,2,3,2,50,50,12,1
Style: Song,Microsoft JhengHei,50,&H00FFFFFF,&H000000FF,&H00A37C00,&H00000000,-1,-1,0,0,100,100,0,0,1,2,2,9,50,50,12,1
Style: Logo,Microsoft JhengHei,45,&H00FFFFFF,&H0000FFFF,&H00000080,&H80000000,-1,0,0,0,100,100,0,0,1,3,1,2,20,20,3,136

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:03.85,Logo,,0,0,0,,此字幕僅供學習交流，請勿用於商業用途。

**Comment by ewwink** [comment]
at line 64 change `SubStyle` to `Logo`
`tmpLines += 'Dialogue: 0,' + line + ',SubStyle,,0,0,0,,'`

from line 84 change `head_str` with your value above

```
head_str = '''[Script Info]
.....
.....
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'''
```

**Comment by pb6210** [comment]
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:03.85,Logo,,0,0,0,,this subtitle for learning only, do not use for commercial purposes.。

Can not be fixed in the program with "Dialogue: 0,0:00:00.00,0:00:03.85,Logo,,0,0,0,,this subtitle for learning only, do not use for commercial purposes.。" This line

**Comment by ewwink** [comment]
please upload your subtitle in .zip so I inspect the problem

**Comment by pb6210** [comment]
head_str = '''[Script Info]
ScriptType: V4.00+
Collisions: Reverse
PlayResX: 1280
PlayResY: 720
Timer: 100.0000
WrapStyle: 0
ScaledBorderAndShadow: no

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Microsoft JhengHei,68,&H0000FFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,3,2,50,50,12,1
Style: Comment,Microsoft JhengHei,40,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,50,50,200,136
Style: Preview,Microsoft JhengHei,65,&H00FFFFFF,&H000000FF,&H00000080,&H64000000,-1,0,0,0,100,100,0,0,1,2,3,1,50,50,12,1
Style: Review,Microsoft JhengHei,65,&H120456DF,&H000000FF,&H00000000,&H00000000,-1,-1,0,0,100,100,0,0,1,2,3,2,50,50,12,1
Style: Song,Microsoft JhengHei,50,&H00FFFFFF,&H000000FF,&H00A37C00,&H00000000,-1,-1,0,0,100,100,0,0,1,2,2,9,50,50,12,1
Style: Logo,Microsoft JhengHei,45,&H00FFFFFF,&H0000FFFF,&H00000080,&H80000000,-1,0,0,0,100,100,0,0,1,3,1,2,20,20,3,136

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:03.85,Logo,,0,0,0,,此字幕僅供學習交流，請勿用於商業用途。\N禁止以任何形式散佈、轉載及公開分享；禁止複製、重製、更改部分或全部內文！'''

    output_str = utf8bom + head_str + '\n' + subLines
    output_str = output_str.encode(encoding)

    with open(output_file, 'wb') as output:
        output.write(output_str)

**Comment by ewwink** [comment]
you mean you got error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1251: ordinal not in range(128)` ?

try this:

```
    head_str = '''[Script Info]
ScriptType: V4.00+
Collisions: Reverse
PlayResX: 1280
PlayResY: 720
Timer: 100.0000
WrapStyle: 0
ScaledBorderAndShadow: no

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Microsoft JhengHei,68,&H0000FFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,3,2,50,50,12,1
Style: Comment,Microsoft JhengHei,40,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,50,50,200,136
Style: Preview,Microsoft JhengHei,65,&H00FFFFFF,&H000000FF,&H00000080,&H64000000,-1,0,0,0,100,100,0,0,1,2,3,1,50,50,12,1
Style: Review,Microsoft JhengHei,65,&H120456DF,&H000000FF,&H00000000,&H00000000,-1,-1,0,0,100,100,0,0,1,2,3,2,50,50,12,1
Style: Song,Microsoft JhengHei,50,&H00FFFFFF,&H000000FF,&H00A37C00,&H00000000,-1,-1,0,0,100,100,0,0,1,2,2,9,50,50,12,1
Style: Logo,Microsoft JhengHei,45,&H00FFFFFF,&H0000FFFF,&H00000080,&H80000000,-1,0,0,0,100,100,0,0,1,3,1,2,20,20,3,136

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:03.85,Logo,,0,0,0,,'''

    unicodeChar = unicode(u'此字幕僅供學習交流，請勿用於商業用途。\\N禁止以任何形式散佈、轉載及公開分享；禁止複製、重製、更改部分或全部內文').encode(encoding)
    head_str += unicodeChar.decode(encoding)

    output_str = utf8bom + head_str + '\n' + subLines
    output_str = output_str.encode(encoding)
```

**Comment by pb6210** [comment]
thank you very much! Solve my problem.
